apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-exchange-service
  labels:
    app: currency-exchange-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-exchange-service
  template:
    metadata:
      labels:
        app: currency-exchange-service
    spec:
      containers:
        - name: currency-exchange-service
          image: tofazzal/currency-exchange-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service-svc
  labels:
    app: currency-exchange-service
spec:
  selector:
    app: currency-exchange-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
